### PR TITLE
Sync

### PR DESCRIPTION
**Pull request by perguth**

### CODE REVIEW

**Comment by perguth** [comment]
Seeing all those `Object.assign` statements I now wonder how it would have looked using `filter`. :smirk:

**Comment by perguth** [comment]
Due the merge 'SET_SONG_DURATION' in `reducers/songs.js` broke.

**Comment by perguth** [comment]
At a9f2460 the force push showed itself on my end:

``` sh
git checkout master
Switched to branch 'master'
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

**Comment by perguth** [comment]
@queicherius Could you check if it works?

**Comment by perguth** [comment]
<strike>Pair</strike>Peerprogramming ftw @queicherius!

**Comment by queicherius** [comment]
:+1:

**Pull request merged**
