### PR TITLE
Mediated downloads

### PR DESCRIPTION
**Pull request by perguth**
**To test:**

_The limit for songs that are stored for friends is set to 1 to allow for easy testing._
1. Connect A to B to C (C needs to be in different browser or incognito tab).
2. Add Songs to A.
3. Refresh B, then C.
4. Download song 1 in C.
5. Check in B that downloading.
6. Quickly download song 2 in C.
7. 1 should be cancelled in B.
8. Wait till song 2 is downloaded in B.
9. Download song 3 in C.
10. Song 2 in B should be deleted.

---

See: peermusic/user-stories/issues/55

### CODE REVIEW

**Comment by queicherius** [comment]
While this does work for me for single downloads, it breaks when you click the "download all" button. I think it's because we are deleting the downloaded file on B before it got transmitted to C [here](https://github.com/peermusic/app/commit/77d50d385f1492e4208f99b3bb4035fbba35c848#diff-933f8a2e640a3186082853bbc788a74fR173). Not 100% sure tho.

> Song 2 in B should be deleted.

The tradeoff of that is, that the remote song doesnt get displayed anymore either until the next sync happens.

Other than that :+1:, pretty cool seeing the files hop from one browser to the next.

**Comment by pguth** [comment]
> While this does work for me for single downloads, it breaks when you click the "download all" button.
That is because of the low storage limit for friends ("The limit for songs that are stored for friends is set to 1 to allow for easy testing."). We can (should :D) increase that.

> The tradeoff of that is, that the remote song doesnt get displayed anymore either until the next sync happens.
Yes, I see that problem too. I relied on the REMOVE_SONG function which also deletes the SONG entry to get rid of the local copy. We should surely replace that call.

**Comment by perguth** [comment]
> While this does work for me for single downloads, it breaks when you click the "download all" button.

That is because of the low storage limit for friends ("The limit for songs that are stored for friends is set to 1 to allow for easy testing."). We can (should :D) increase that.

> The tradeoff of that is, that the remote song doesnt get displayed anymore either until the next sync happens.

Yes, I see that problem too. I relied on the REMOVE_SONG function which also deletes the SONG entry to get rid of the local copy. We should surely replace that call.

**Comment by perguth** [comment]
@queicherius I increased the pending value and created a new ticket for the disappearing track: peermusic/user-stories/issues/99

Merge?

**Comment by queicherius** [comment]
Yeah, let's merge. :shipit:

**Pull request merged**
